[build-system]
requires = [
    "speculos>=0.1.85",
    "ledgercomm",
    "ledgercomm[hid]",
    "ledgerwallet==0.1.3",
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.mypy]
ignore_missing_imports = true

[tool.yapf]
based_on_style = "pep8"
column_limit = 100
