[build-system]
requires = [
    "speculos",
    "ledgercomm",
    "ledgerwallet==0.1.3",
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.mypy]
ignore_missing_imports = true
