[build-system]
requires = [
    "setuptools>=45",
    "setuptools_scm[toml]>=6.2",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/ragger/__version__.py"
tag_regex = "((?P<destination>test)-)?v(?P<version>(\\d\\.){2}\\d)"
fallback_version = "0.0.0"

[tool.mypy]
ignore_missing_imports = true

[tool.yapf]
based_on_style = "pep8"
column_limit = 100

[tool.coverage.report]
show_missing = true
exclude_lines = [
    "@abstractmethod",
    "pragma: no cover"
]
