name: Build, test and deploy ragger

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop
      - master

jobs:
  build_install_test:
    name: Build, install and test the library
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v2
    - name: Speculos dependencies
      run: sudo apt-get update && sudo apt-get install -y qemu-user-static
    - name: Build & install
      run: pip install --extra-index-url https://test.pypi.org/simple/ -U .[tests]
    - name: Gather an application to run tests against
      uses: dawidd6/action-download-artifact@v2
      with:
        repo: LedgerHQ/app-boilerplate
        name: boilerplate-app-nanoS
        workflow: ci-workflow.yml
        path: tests/elfs/
    - name: Check the downloaded files
      run: tree .
    - name: Run tests
      run: pytest tests/

  package_and_deploy:
    name: Build and deploy Ragger Python Package
    needs: [build_install_test]
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install Ragger
      run: pip install --extra-index-url https://test.pypi.org/simple/ .
    - name: Build Ragger python package
      run: |
        pip install --upgrade pip build twine
        PIP_EXTRA_INDEX_URL=https://test.pypi.org/simple/ python -m build
        python -m twine check dist/*
    # TEST_PYPI_API_TOKEN is an API token created on
    # https://test.pypi.org/manage/account/#api-tokens with restriction to speculos project
    - name: Publish Python package to test.pypi.org
      if: success() && github.event_name == 'push' && github.ref == 'refs/heads/develop'
      run: python -m twine upload --repository testpypi dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PUBLIC_API_TOKEN  }}
        TWINE_NON_INTERACTIVE: 1
