name: Build and test Ragger

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build_boilerplate_application:
    name: Build boilerplate application using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1
    with:
      app_repository: LedgerHQ/app-boilerplate
      app_branch_name: master
      upload_app_binaries_artifact: boilerplate_binaries

  build_install_test:
    name: Install and test the library
    needs: build_boilerplate_application
    runs-on: ubuntu-latest

    steps:
    - name: Clone
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Speculos dependencies
      run: sudo apt-get update && sudo apt-get install -y qemu-user-static tesseract-ocr libtesseract-dev

    - name: Build & install
      run: |
        pip install --extra-index-url https://test.pypi.org/simple/ -U .[tests,all_backends]
        pip install -U click>=8

    - name: Download app binaries
      uses: actions/download-artifact@v3
      with:
        name: boilerplate_binaries
        path: ./build/

    - name: Check the downloaded files
      run: tree .

    - name: Run tests and generate coverage
      run: pytest -v --tb=short tests/ --cov ragger --cov-report xml --device all

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        name: codecov-ragger
